# specfile generated by rpmerizor (http://sourceforge.net/projects/rpmerizor/)

# if you are using __spec_only and want to build rpm package
# after, from command line, you have to use the following syntaxe
# rpmbuild -bb --buildroot=/tmp/rpmerizor_buildroot your_specfile.spec

# supported algorithm (cf rpmsign)
# may be SHA1, SHA256, SHA384, and SHA512
# represented as 2, 8, 9, and 10 respectively
# use 1 for md5 for compatibility with rpm < 4.6.0
# %global _binary_filedigest_algorithm 1
# %global _source_filedigest_algorithm 1

%define _build_id_links none
%define defaultbuildroot /
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0

%define name    llvm-21-python3-local
%define version 21.1.8

Summary: The LLVM Compiler Infrastructure.
Name: %{name}
Version: %{version}
Release: 300.fc41
License: Apache 2.0 with LLVM Exception
Group: C and C++ Development Tools and Libraries
BuildArch: x86_64
URL: https://llvm.org/
Packager: Stefan Teleman <stefan.teleman@ieee.org>
# autoreq and autoprov
AutoReqProv: yes

%description
Python 3.13 Bindings for LLVM. The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. Despite its name, LLVM has little to do with traditional virtual machines. The name 'LLVM' itself is not an acronym; it is the full name of the project.

%prep
ln -s /src/steleman/programming/llvm-21.1.8/install-llvm-python3 /tmp/rpmerizor_buildroot

%clean
rm /tmp/rpmerizor_buildroot

%files
%dir /usr/local/lib64/python3.13/site-packages/lldb
%dir /usr/local/lib64/python3.13/site-packages/lldb/formatters
%dir /usr/local/lib64/python3.13/site-packages/lldb/formatters/cpp
%dir /usr/local/lib64/python3.13/site-packages/lldb/plugins
%dir /usr/local/lib64/python3.13/site-packages/lldb/utils
%dir /usr/local/lib64/python3.13/site-packages/mlir_core
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlir
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlir/dialects
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlir/dialects/transform
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Bindings
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Bindings/Python
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Transform
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Target
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/async_dialect
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/async_dialect/passes
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/gpu
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/gpu/passes
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/lang
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/ops
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/passes
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/extras
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/interpreter
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/extras
%dir /usr/local/lib64/python3.13/site-packages/mlir_core/mlir/runtime
/usr/local/lib64/python3.13/site-packages/lldb/_lldb.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/lldb/lldb-argdumper
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/libMLIRPythonCAPI.so
/usr/local/lib64/python3.13/site-packages/lldb/__init__.py
/usr/local/lib64/python3.13/site-packages/lldb/embedded_interpreter.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/Logger.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/__init__.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/attrib_fromdict.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/cache.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/cpp/__init__.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/cpp/gnu_libstdcpp.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/cpp/libcxx.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/metrics.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/synth.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/__init__.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/operating_system.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/parsed_cmd.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/scripted_platform.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/scripted_process.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/scripted_thread_plan.py
/usr/local/lib64/python3.13/site-packages/lldb/utils/__init__.py
/usr/local/lib64/python3.13/site-packages/lldb/utils/in_call_stack.py
/usr/local/lib64/python3.13/site-packages/lldb/utils/symbolication.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlir.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlir/__init__.pyi
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlir/dialects/pdl.pyi
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlir/dialects/quant.pyi
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlir/dialects/transform/__init__.pyi
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlir/ir.pyi
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlir/passmanager.pyi
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirAsyncPasses.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirDialectsGPU.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirDialectsLLVM.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirDialectsLinalg.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirDialectsNVGPU.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirDialectsPDL.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirDialectsQuant.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirDialectsSMT.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirDialectsSparseTensor.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirDialectsTransform.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirExecutionEngine.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirExecutionEngine.pyi
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirGPUPasses.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirLinalgPasses.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirPythonTestNanobind.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirPythonTestPybind11.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirRegisterEverything.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirSparseTensorPasses.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/_mlirTransformInterpreter.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/AffineExpr.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/AffineMap.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Bindings/Python/Interop.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/BuiltinAttributes.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/BuiltinTypes.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Conversion.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Debug.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Diagnostics.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/AMDGPU.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Arith.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Async.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/ControlFlow.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/EmitC.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Func.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/GPU.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/IRDL.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Index.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/LLVM.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Linalg.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/MLProgram.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Math.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/MemRef.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/NVGPU.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/NVVM.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/OpenMP.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/PDL.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Quant.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/ROCDL.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/SCF.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/SMT.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/SPIRV.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Shape.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/SparseTensor.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Tensor.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Transform.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Transform/Interpreter.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Dialect/Vector.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/ExecutionEngine.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/IR.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/IntegerSet.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Interfaces.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Pass.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/RegisterEverything.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Rewrite.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Support.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Target/ExportSMTLIB.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Target/LLVMIR.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/include/mlir-c/Transforms.h
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/_mlir_libs/libMLIRPythonCAPI.so.21.1
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_affine_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_affine_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_amdgpu_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_amdgpu_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_arith_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_arith_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_async_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_bufferization_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_bufferization_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_bufferization_transform_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_builtin_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_cf_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_complex_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_emitc_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_func_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_gpu_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_gpu_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_gpu_transform_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_index_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_index_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_linalg_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_linalg_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_llvm_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_llvm_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_loop_transform_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_math_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_memref_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_memref_transform_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_ml_program_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_nvgpu_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_nvgpu_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_nvgpu_transform_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_nvvm_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_nvvm_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_ods_common.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_omp_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_pdl_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_python_test_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_rocdl_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_scf_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_shape_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_smt_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_smt_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_sparse_tensor_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_sparse_tensor_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_sparse_tensor_transform_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_spirv_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_structured_transform_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_structured_transform_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_tensor_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_tensor_transform_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_tosa_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_transform_debug_extension_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_transform_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_transform_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_transform_pdl_extension_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_transform_tune_extension_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_vector_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_vector_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_vector_transform_enum_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/_vector_transform_ops_gen.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/affine.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/amdgpu.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/arith.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/async_dialect/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/async_dialect/passes/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/bufferization.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/builtin.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/cf.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/complex.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/emitc.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/func.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/gpu/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/gpu/passes/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/index.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/dump_oplib.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/lang/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/lang/affine.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/lang/comprehension.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/lang/config.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/lang/dsl.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/lang/emitter.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/lang/scalar_expr.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/lang/types.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/lang/yaml_helper.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/ops/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/opdsl/ops/core_named_ops.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/linalg/passes/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/llvm.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/math.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/memref.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/ml_program.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/nvgpu.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/nvvm.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/openmp.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/pdl.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/python_test.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/quant.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/rocdl.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/scf.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/shape.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/smt.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/sparse_tensor.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/spirv.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/tensor.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/tosa.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/bufferization.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/debug.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/extras/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/gpu.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/interpreter/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/loop.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/memref.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/nvgpu.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/pdl.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/sparse_tensor.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/structured.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/tensor.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/tune.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/transform/vector.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/dialects/vector.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/execution_engine.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/extras/meta.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/extras/types.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/ir.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/passmanager.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/rewrite.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/runtime/__init__.py
/usr/local/lib64/python3.13/site-packages/mlir_core/mlir/runtime/np_to_memref.py

