# specfile generated by rpmerizor (http://sourceforge.net/projects/rpmerizor/)

# if you are using __spec_only and want to build rpm package
# after, from command line, you have to use the following syntaxe
# rpmbuild -bb --buildroot=/tmp/rpmerizor_buildroot your_specfile.spec

# supported algorithm (cf rpmsign)
# may be SHA1, SHA256, SHA384, and SHA512
# represented as 2, 8, 9, and 10 respectively
# use 1 for md5 for compatibility with rpm < 4.6.0
# %global _binary_filedigest_algorithm 1
# %global _source_filedigest_algorithm 1

%define _build_id_links none
%define defaultbuildroot /
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0

%define name    llvm-21-src-local
%define version 21.1.8

Summary: The LLVM Compiler Infrastructure.
Name: %{name}
Version: %{version}
Release: 300.fc41
License: Apache 2.0 with LLVM Exception
Group: C and C++ Development Tools and Libraries
BuildArch: x86_64
URL: https://llvm.org/
Packager: Stefan Teleman <stefan.teleman@ieee.org>
# autoreq and autoprov
AutoReqProv: yes

%description
Python and Pybind11 Bindings for MLIR. The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. Despite its name, LLVM has little to do with traditional virtual machines. The name 'LLVM' itself is not an acronym; it is the full name of the project.

%prep
ln -s /src/steleman/programming/llvm-21.1.8/install-llvm-src /tmp/rpmerizor_buildroot

%clean
rm /tmp/rpmerizor_buildroot

%files
%dir /opt/llvm/21.1.8
%dir /opt/llvm/21.1.8/src
%dir /opt/llvm/21.1.8/src/python
%dir /opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources
%dir /opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c
%dir /opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Bindings
%dir /opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Bindings/Python
%dir /opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect
%dir /opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Target
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.AsyncDialectPasses
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.GPU.Pybind
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.LLVM.Pybind
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.Linalg.Pybind
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.NVGPU.Pybind
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.PDL.Pybind
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.Quant.Pybind
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.SMT.Pybind
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.SparseTensor.Pybind
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.Transform.Pybind
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.ExecutionEngine
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.GPUDialectPasses
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.LinalgPasses
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.RegisterEverything
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.SparseTensorDialectPasses
%dir /opt/llvm/21.1.8/src/python/MLIRPythonExtension.TransformInterpreter
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python.Extras
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python.Extras/extras
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/_mlir_libs
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/_mlir_libs/_mlir
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.affine
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.affine.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.affine.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.affine/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.amdgpu
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.amdgpu.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.amdgpu.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.amdgpu/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.arith
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.arith.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.arith.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.arith/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.async
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.async.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.async.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.async/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.async/dialects/async_dialect
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.async/dialects/async_dialect/passes
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization_transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization_transform.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization_transform.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization_transform/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization_transform/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.builtin
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.builtin.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.builtin.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.builtin/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.cf
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.cf.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.cf.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.cf/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.complex
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.complex.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.complex.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.complex/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.emitc
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.emitc.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.emitc.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.emitc/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.func
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.func.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.func.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.func/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu/dialects/gpu
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu/dialects/gpu/passes
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu_transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu_transform.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu_transform.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu_transform/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu_transform/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.index
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.index.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.index.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.index/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/lang
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/ops
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/passes
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.llvm
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.llvm.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.llvm.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.llvm/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.loop_transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.loop_transform.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.loop_transform.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.loop_transform/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.loop_transform/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.math
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.math.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.math.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.math/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref_transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref_transform.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref_transform.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref_transform/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref_transform/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.ml_program
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.ml_program.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.ml_program.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.ml_program/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu_transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu_transform.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu_transform.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu_transform/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu_transform/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvvm
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvvm.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvvm.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvvm/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.omp
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.omp.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.omp.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.omp/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.pdl
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.pdl.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.pdl.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.pdl/_mlir_libs
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.pdl/_mlir_libs/_mlir
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.pdl/_mlir_libs/_mlir/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.pdl/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.quant
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.quant/_mlir_libs
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.quant/_mlir_libs/_mlir
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.quant/_mlir_libs/_mlir/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.quant/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.rocdl
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.rocdl.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.rocdl.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.rocdl/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.scf
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.scf.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.scf.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.scf/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.shape
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.shape.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.shape.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.shape/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.smt
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.smt.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.smt.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.smt/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor_transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor_transform.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor_transform.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor_transform/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor_transform/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.spirv
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.spirv.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.spirv.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.spirv/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.structured_transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.structured_transform.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.structured_transform.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.structured_transform/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.structured_transform/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor_transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor_transform.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor_transform.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor_transform/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor_transform/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tosa
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tosa.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tosa.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tosa/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.extras
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.extras/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.extras/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.extras/dialects/transform/extras
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.interpreter
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.interpreter/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.interpreter/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.interpreter/dialects/transform/interpreter
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform/_mlir_libs
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform/_mlir_libs/_mlir
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform/_mlir_libs/_mlir/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform/_mlir_libs/_mlir/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_debug_extension
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_debug_extension.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_debug_extension.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_debug_extension/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_debug_extension/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_pdl_extension
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_pdl_extension.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_pdl_extension.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_pdl_extension/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_pdl_extension/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_tune_extension
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_tune_extension.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_tune_extension.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_tune_extension/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_tune_extension/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector_transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector_transform.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector_transform.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector_transform/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector_transform/dialects/transform
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.ExecutionEngine
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.ExecutionEngine/_mlir_libs
%dir /opt/llvm/21.1.8/src/python/MLIRPythonSources.ExecutionEngine/runtime
%dir /opt/llvm/21.1.8/src/python/MLIRPythonTestSources.Dialects.PythonTest
%dir /opt/llvm/21.1.8/src/python/MLIRPythonTestSources.Dialects.PythonTest.ops_gen
%dir /opt/llvm/21.1.8/src/python/MLIRPythonTestSources.Dialects.PythonTest.ops_gen/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonTestSources.Dialects.PythonTest/dialects
%dir /opt/llvm/21.1.8/src/python/MLIRPythonTestSources.PythonTestExtensionNanobind
%dir /opt/llvm/21.1.8/src/python/MLIRPythonTestSources.PythonTestExtensionPybind11
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/AffineExpr.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/AffineMap.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Bindings/Python/Interop.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/BuiltinAttributes.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/BuiltinTypes.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Conversion.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Debug.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Diagnostics.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/AMDGPU.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Arith.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Async.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/ControlFlow.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/EmitC.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Func.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/GPU.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/IRDL.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Index.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/LLVM.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Linalg.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/MLProgram.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Math.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/MemRef.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/NVGPU.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/NVVM.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/OpenMP.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/PDL.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Quant.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/ROCDL.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/SCF.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/SMT.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/SPIRV.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Shape.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/SparseTensor.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Tensor.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Transform.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Transform/Interpreter.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Dialect/Vector.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/ExecutionEngine.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/IR.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/IntegerSet.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Interfaces.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Pass.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/RegisterEverything.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Rewrite.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Support.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Target/ExportSMTLIB.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Target/LLVMIR.h
/opt/llvm/21.1.8/src/python/MLIRPythonCAPI.HeaderSources/mlir-c/Transforms.h
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.AsyncDialectPasses/AsyncPasses.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/Globals.h
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/IRAffine.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/IRAttributes.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/IRCore.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/IRInterfaces.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/IRModule.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/IRModule.h
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/IRTypes.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/MainModule.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/NanobindUtils.h
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/Pass.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/Pass.h
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/Rewrite.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Core/Rewrite.h
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.GPU.Pybind/DialectGPU.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.LLVM.Pybind/DialectLLVM.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.Linalg.Pybind/DialectLinalg.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.NVGPU.Pybind/DialectNVGPU.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.PDL.Pybind/DialectPDL.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.Quant.Pybind/DialectQuant.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.SMT.Pybind/DialectSMT.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.SMT.Pybind/NanobindUtils.h
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.SparseTensor.Pybind/DialectSparseTensor.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.Dialects.Transform.Pybind/DialectTransform.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.ExecutionEngine/ExecutionEngineModule.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.GPUDialectPasses/GPUPasses.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.LinalgPasses/LinalgPasses.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.RegisterEverything/RegisterEverything.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.SparseTensorDialectPasses/SparseTensorPasses.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonExtension.TransformInterpreter/TransformInterpreter.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python.Extras/extras/meta.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python.Extras/extras/types.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/_mlir_libs/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/_mlir_libs/_mlir/__init__.pyi
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/_mlir_libs/_mlir/ir.pyi
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/_mlir_libs/_mlir/passmanager.pyi
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/dialects/_ods_common.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/ir.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/passmanager.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Core.Python/rewrite.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.affine.ops_gen/dialects/_affine_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.affine.ops_gen/dialects/_affine_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.affine/dialects/affine.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.amdgpu.ops_gen/dialects/_amdgpu_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.amdgpu.ops_gen/dialects/_amdgpu_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.amdgpu/dialects/amdgpu.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.arith.ops_gen/dialects/_arith_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.arith.ops_gen/dialects/_arith_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.arith/dialects/arith.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.async.ops_gen/dialects/_async_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.async/dialects/async_dialect/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.async/dialects/async_dialect/passes/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization.ops_gen/dialects/_bufferization_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization.ops_gen/dialects/_bufferization_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization/dialects/bufferization.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization_transform.ops_gen/dialects/_bufferization_transform_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.bufferization_transform/dialects/transform/bufferization.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.builtin.ops_gen/dialects/_builtin_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.builtin/dialects/builtin.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.cf.ops_gen/dialects/_cf_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.cf/dialects/cf.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.complex.ops_gen/dialects/_complex_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.complex/dialects/complex.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.emitc.ops_gen/dialects/_emitc_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.emitc/dialects/emitc.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.func.ops_gen/dialects/_func_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.func/dialects/func.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu.ops_gen/dialects/_gpu_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu.ops_gen/dialects/_gpu_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu/dialects/gpu/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu/dialects/gpu/passes/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu_transform.ops_gen/dialects/_gpu_transform_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.gpu_transform/dialects/transform/gpu.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.index.ops_gen/dialects/_index_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.index.ops_gen/dialects/_index_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.index/dialects/index.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg.ops_gen/dialects/_linalg_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg.ops_gen/dialects/_linalg_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/dump_oplib.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/lang/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/lang/affine.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/lang/comprehension.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/lang/config.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/lang/dsl.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/lang/emitter.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/lang/scalar_expr.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/lang/types.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/lang/yaml_helper.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/ops/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/opdsl/ops/core_named_ops.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.linalg/dialects/linalg/passes/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.llvm.ops_gen/dialects/_llvm_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.llvm.ops_gen/dialects/_llvm_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.llvm/dialects/llvm.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.loop_transform.ops_gen/dialects/_loop_transform_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.loop_transform/dialects/transform/loop.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.math.ops_gen/dialects/_math_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.math/dialects/math.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref.ops_gen/dialects/_memref_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref/dialects/memref.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref_transform.ops_gen/dialects/_memref_transform_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.memref_transform/dialects/transform/memref.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.ml_program.ops_gen/dialects/_ml_program_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.ml_program/dialects/ml_program.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu.ops_gen/dialects/_nvgpu_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu.ops_gen/dialects/_nvgpu_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu/dialects/nvgpu.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu_transform.ops_gen/dialects/_nvgpu_transform_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvgpu_transform/dialects/transform/nvgpu.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvvm.ops_gen/dialects/_nvvm_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvvm.ops_gen/dialects/_nvvm_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.nvvm/dialects/nvvm.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.omp.ops_gen/dialects/_omp_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.omp/dialects/openmp.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.pdl.ops_gen/dialects/_pdl_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.pdl/_mlir_libs/_mlir/dialects/pdl.pyi
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.pdl/dialects/pdl.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.quant/_mlir_libs/_mlir/dialects/quant.pyi
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.quant/dialects/quant.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.rocdl.ops_gen/dialects/_rocdl_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.rocdl/dialects/rocdl.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.scf.ops_gen/dialects/_scf_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.scf/dialects/scf.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.shape.ops_gen/dialects/_shape_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.shape/dialects/shape.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.smt.ops_gen/dialects/_smt_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.smt.ops_gen/dialects/_smt_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.smt/dialects/smt.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor.ops_gen/dialects/_sparse_tensor_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor.ops_gen/dialects/_sparse_tensor_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor/dialects/sparse_tensor.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor_transform.ops_gen/dialects/_sparse_tensor_transform_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.sparse_tensor_transform/dialects/transform/sparse_tensor.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.spirv.ops_gen/dialects/_spirv_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.spirv/dialects/spirv.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.structured_transform.ops_gen/dialects/_structured_transform_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.structured_transform.ops_gen/dialects/_structured_transform_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.structured_transform/dialects/transform/structured.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor.ops_gen/dialects/_tensor_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor/dialects/tensor.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor_transform.ops_gen/dialects/_tensor_transform_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tensor_transform/dialects/transform/tensor.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tosa.ops_gen/dialects/_tosa_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.tosa/dialects/tosa.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.extras/dialects/transform/extras/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.interpreter/dialects/transform/interpreter/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.ops_gen/dialects/_transform_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform.ops_gen/dialects/_transform_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform/_mlir_libs/_mlir/dialects/transform/__init__.pyi
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform/dialects/transform/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_debug_extension.ops_gen/dialects/_transform_debug_extension_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_debug_extension/dialects/transform/debug.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_pdl_extension.ops_gen/dialects/_transform_pdl_extension_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_pdl_extension/dialects/transform/pdl.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_tune_extension.ops_gen/dialects/_transform_tune_extension_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.transform_tune_extension/dialects/transform/tune.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector.ops_gen/dialects/_vector_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector.ops_gen/dialects/_vector_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector/dialects/vector.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector_transform.ops_gen/dialects/_vector_transform_enum_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector_transform.ops_gen/dialects/_vector_transform_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.Dialects.vector_transform/dialects/transform/vector.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.ExecutionEngine/_mlir_libs/_mlirExecutionEngine.pyi
/opt/llvm/21.1.8/src/python/MLIRPythonSources.ExecutionEngine/execution_engine.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.ExecutionEngine/runtime/__init__.py
/opt/llvm/21.1.8/src/python/MLIRPythonSources.ExecutionEngine/runtime/np_to_memref.py
/opt/llvm/21.1.8/src/python/MLIRPythonTestSources.Dialects.PythonTest.ops_gen/dialects/_python_test_ops_gen.py
/opt/llvm/21.1.8/src/python/MLIRPythonTestSources.Dialects.PythonTest/dialects/python_test.py
/opt/llvm/21.1.8/src/python/MLIRPythonTestSources.PythonTestExtensionNanobind/PythonTestModuleNanobind.cpp
/opt/llvm/21.1.8/src/python/MLIRPythonTestSources.PythonTestExtensionPybind11/PythonTestModulePybind11.cpp

