# specfile generated by rpmerizor (http://sourceforge.net/projects/rpmerizor/)

# if you are using __spec_only and want to build rpm package
# after, from command line, you have to use the following syntaxe
# rpmbuild -bb --buildroot=/tmp/rpmerizor_buildroot your_specfile.spec

# supported algorithm (cf rpmsign)
# may be SHA1, SHA256, SHA384, and SHA512
# represented as 2, 8, 9, and 10 respectively
# use 1 for md5 for compatibility with rpm < 4.6.0
# %global _binary_filedigest_algorithm 1
# %global _source_filedigest_algorithm 1

%define _build_id_links none
%define defaultbuildroot /
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0

%define name    llvm-21-examples-local
%define version 21.1.8

Summary: The LLVM Compiler Infrastructure.
Name: %{name}
Version: %{version}
Release: 300.fc41
License: Apache 2.0 with LLVM Exception
Group: C and C++ Development Tools and Libraries
BuildArch: x86_64
URL: https://llvm.org/
Packager: Stefan Teleman <stefan.teleman@ieee.org>
# autoreq and autoprov
AutoReqProv: yes

%description
Examples for LLVM and MLIR. The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. Despite its name, LLVM has little to do with traditional virtual machines. The name 'LLVM' itself is not an acronym; it is the full name of the project.

%prep
ln -s /src/steleman/programming/llvm-21.1.8/install-llvm-examples /tmp/rpmerizor_buildroot

%clean
rm /tmp/rpmerizor_buildroot

%files
%dir /opt/llvm/21.1.8
%dir /opt/llvm/21.1.8/examples
/opt/llvm/21.1.8/examples/BrainF
/opt/llvm/21.1.8/examples/BuildingAJIT-Ch1
/opt/llvm/21.1.8/examples/BuildingAJIT-Ch2
/opt/llvm/21.1.8/examples/BuildingAJIT-Ch3
/opt/llvm/21.1.8/examples/BuildingAJIT-Ch4
/opt/llvm/21.1.8/examples/ExceptionDemo
/opt/llvm/21.1.8/examples/Fibonacci
/opt/llvm/21.1.8/examples/HowToUseJIT
/opt/llvm/21.1.8/examples/HowToUseLLJIT
/opt/llvm/21.1.8/examples/Kaleidoscope-Ch2
/opt/llvm/21.1.8/examples/Kaleidoscope-Ch3
/opt/llvm/21.1.8/examples/Kaleidoscope-Ch4
/opt/llvm/21.1.8/examples/Kaleidoscope-Ch5
/opt/llvm/21.1.8/examples/Kaleidoscope-Ch6
/opt/llvm/21.1.8/examples/Kaleidoscope-Ch7
/opt/llvm/21.1.8/examples/Kaleidoscope-Ch8
/opt/llvm/21.1.8/examples/Kaleidoscope-Ch9
/opt/llvm/21.1.8/examples/LLJITDumpObjects
/opt/llvm/21.1.8/examples/LLJITRemovableCode
/opt/llvm/21.1.8/examples/LLJITWithCustomObjectLinkingLayer
/opt/llvm/21.1.8/examples/LLJITWithExecutorProcessControl
/opt/llvm/21.1.8/examples/LLJITWithGDBRegistrationListener
/opt/llvm/21.1.8/examples/LLJITWithInitializers
/opt/llvm/21.1.8/examples/LLJITWithLazyReexports
/opt/llvm/21.1.8/examples/LLJITWithObjectCache
/opt/llvm/21.1.8/examples/LLJITWithObjectLinkingLayerPlugin
/opt/llvm/21.1.8/examples/LLJITWithOptimizingIRTransform
/opt/llvm/21.1.8/examples/LLJITWithRemoteDebugging
/opt/llvm/21.1.8/examples/LLJITWithThinLTOSummaries
/opt/llvm/21.1.8/examples/ModuleMaker
/opt/llvm/21.1.8/examples/OrcV2CBindingsAddObjectFile
/opt/llvm/21.1.8/examples/OrcV2CBindingsBasicUsage
/opt/llvm/21.1.8/examples/OrcV2CBindingsDumpObjects
/opt/llvm/21.1.8/examples/OrcV2CBindingsIRTransforms
/opt/llvm/21.1.8/examples/OrcV2CBindingsLazy
/opt/llvm/21.1.8/examples/OrcV2CBindingsMCJITLikeMemoryManager
/opt/llvm/21.1.8/examples/OrcV2CBindingsRemovableCode
/opt/llvm/21.1.8/examples/OrcV2CBindingsVeryLazy
/opt/llvm/21.1.8/examples/ParallelJIT
/opt/llvm/21.1.8/examples/SpeculativeJIT
/opt/llvm/21.1.8/examples/toyc-ch1
/opt/llvm/21.1.8/examples/toyc-ch2
/opt/llvm/21.1.8/examples/toyc-ch3
/opt/llvm/21.1.8/examples/toyc-ch4
/opt/llvm/21.1.8/examples/toyc-ch5
/opt/llvm/21.1.8/examples/toyc-ch6
/opt/llvm/21.1.8/examples/toyc-ch7
/opt/llvm/21.1.8/examples/transform-opt-ch2
/opt/llvm/21.1.8/examples/transform-opt-ch3
/opt/llvm/21.1.8/examples/transform-opt-ch4

