# specfile generated by rpmerizor (http://sourceforge.net/projects/rpmerizor/)

# if you are using __spec_only and want to build rpm package
# after, from command line, you have to use the following syntaxe
# rpmbuild -bb --buildroot=/tmp/rpmerizor_buildroot your_specfile.spec

# supported algorithm (cf rpmsign)
# may be SHA1, SHA256, SHA384, and SHA512
# represented as 2, 8, 9, and 10 respectively
# use 1 for md5 for compatibility with rpm < 4.6.0
# %global _binary_filedigest_algorithm 1
# %global _source_filedigest_algorithm 1

%define _build_id_links none
%define defaultbuildroot /
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0

%define name    llvm-21-ocaml-local
%define version 21.1.8

Summary: The LLVM Compiler Infrastructure.
Name: %{name}
Version: %{version}
Release: 300.fc41
License: Apache 2.0 with LLVM Exception
Group: C and C++ Development Tools and Libraries
BuildArch: x86_64
URL: https://llvm.org/
Packager: Stefan Teleman <stefan.teleman@ieee.org>
# autoreq and autoprov
AutoReqProv: yes

%description
OCaml Bindings for LLVM. The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. Despite its name, LLVM has little to do with traditional virtual machines. The name 'LLVM' itself is not an acronym; it is the full name of the project.

%prep
ln -s /src/steleman/programming/llvm-21.1.8/install-llvm-ocaml /tmp/rpmerizor_buildroot

%clean
rm /tmp/rpmerizor_buildroot

%files
%dir /usr/lib64/ocaml
%dir /usr/lib64/ocaml/llvm
/usr/lib64/ocaml/META.llvm
/usr/lib64/ocaml/META.llvm_AMDGPU
/usr/lib64/ocaml/META.llvm_NVPTX
/usr/lib64/ocaml/META.llvm_X86
/usr/lib64/ocaml/llvm/libllvm.a
/usr/lib64/ocaml/llvm/libllvm_AMDGPU.a
/usr/lib64/ocaml/llvm/libllvm_NVPTX.a
/usr/lib64/ocaml/llvm/libllvm_X86.a
/usr/lib64/ocaml/llvm/libllvm_all_backends.a
/usr/lib64/ocaml/llvm/libllvm_analysis.a
/usr/lib64/ocaml/llvm/libllvm_bitreader.a
/usr/lib64/ocaml/llvm/libllvm_bitwriter.a
/usr/lib64/ocaml/llvm/libllvm_debuginfo.a
/usr/lib64/ocaml/llvm/libllvm_executionengine.a
/usr/lib64/ocaml/llvm/libllvm_irreader.a
/usr/lib64/ocaml/llvm/libllvm_linker.a
/usr/lib64/ocaml/llvm/libllvm_passbuilder.a
/usr/lib64/ocaml/llvm/libllvm_target.a
/usr/lib64/ocaml/llvm/libllvm_transform_utils.a
/usr/lib64/ocaml/llvm/llvm.a
/usr/lib64/ocaml/llvm/llvm.cma
/usr/lib64/ocaml/llvm/llvm.cmi
/usr/lib64/ocaml/llvm/llvm.cmt
/usr/lib64/ocaml/llvm/llvm.cmti
/usr/lib64/ocaml/llvm/llvm.cmx
/usr/lib64/ocaml/llvm/llvm.cmxa
/usr/lib64/ocaml/llvm/llvm.mli
/usr/lib64/ocaml/llvm/llvm_AMDGPU.a
/usr/lib64/ocaml/llvm/llvm_AMDGPU.cma
/usr/lib64/ocaml/llvm/llvm_AMDGPU.cmi
/usr/lib64/ocaml/llvm/llvm_AMDGPU.cmt
/usr/lib64/ocaml/llvm/llvm_AMDGPU.cmti
/usr/lib64/ocaml/llvm/llvm_AMDGPU.cmx
/usr/lib64/ocaml/llvm/llvm_AMDGPU.cmxa
/usr/lib64/ocaml/llvm/llvm_AMDGPU.mli
/usr/lib64/ocaml/llvm/llvm_NVPTX.a
/usr/lib64/ocaml/llvm/llvm_NVPTX.cma
/usr/lib64/ocaml/llvm/llvm_NVPTX.cmi
/usr/lib64/ocaml/llvm/llvm_NVPTX.cmt
/usr/lib64/ocaml/llvm/llvm_NVPTX.cmti
/usr/lib64/ocaml/llvm/llvm_NVPTX.cmx
/usr/lib64/ocaml/llvm/llvm_NVPTX.cmxa
/usr/lib64/ocaml/llvm/llvm_NVPTX.mli
/usr/lib64/ocaml/llvm/llvm_X86.a
/usr/lib64/ocaml/llvm/llvm_X86.cma
/usr/lib64/ocaml/llvm/llvm_X86.cmi
/usr/lib64/ocaml/llvm/llvm_X86.cmt
/usr/lib64/ocaml/llvm/llvm_X86.cmti
/usr/lib64/ocaml/llvm/llvm_X86.cmx
/usr/lib64/ocaml/llvm/llvm_X86.cmxa
/usr/lib64/ocaml/llvm/llvm_X86.mli
/usr/lib64/ocaml/llvm/llvm_all_backends.a
/usr/lib64/ocaml/llvm/llvm_all_backends.cma
/usr/lib64/ocaml/llvm/llvm_all_backends.cmi
/usr/lib64/ocaml/llvm/llvm_all_backends.cmt
/usr/lib64/ocaml/llvm/llvm_all_backends.cmti
/usr/lib64/ocaml/llvm/llvm_all_backends.cmx
/usr/lib64/ocaml/llvm/llvm_all_backends.cmxa
/usr/lib64/ocaml/llvm/llvm_all_backends.mli
/usr/lib64/ocaml/llvm/llvm_analysis.a
/usr/lib64/ocaml/llvm/llvm_analysis.cma
/usr/lib64/ocaml/llvm/llvm_analysis.cmi
/usr/lib64/ocaml/llvm/llvm_analysis.cmt
/usr/lib64/ocaml/llvm/llvm_analysis.cmti
/usr/lib64/ocaml/llvm/llvm_analysis.cmx
/usr/lib64/ocaml/llvm/llvm_analysis.cmxa
/usr/lib64/ocaml/llvm/llvm_analysis.mli
/usr/lib64/ocaml/llvm/llvm_bitreader.a
/usr/lib64/ocaml/llvm/llvm_bitreader.cma
/usr/lib64/ocaml/llvm/llvm_bitreader.cmi
/usr/lib64/ocaml/llvm/llvm_bitreader.cmt
/usr/lib64/ocaml/llvm/llvm_bitreader.cmti
/usr/lib64/ocaml/llvm/llvm_bitreader.cmx
/usr/lib64/ocaml/llvm/llvm_bitreader.cmxa
/usr/lib64/ocaml/llvm/llvm_bitreader.mli
/usr/lib64/ocaml/llvm/llvm_bitwriter.a
/usr/lib64/ocaml/llvm/llvm_bitwriter.cma
/usr/lib64/ocaml/llvm/llvm_bitwriter.cmi
/usr/lib64/ocaml/llvm/llvm_bitwriter.cmt
/usr/lib64/ocaml/llvm/llvm_bitwriter.cmti
/usr/lib64/ocaml/llvm/llvm_bitwriter.cmx
/usr/lib64/ocaml/llvm/llvm_bitwriter.cmxa
/usr/lib64/ocaml/llvm/llvm_bitwriter.mli
/usr/lib64/ocaml/llvm/llvm_debuginfo.a
/usr/lib64/ocaml/llvm/llvm_debuginfo.cma
/usr/lib64/ocaml/llvm/llvm_debuginfo.cmi
/usr/lib64/ocaml/llvm/llvm_debuginfo.cmt
/usr/lib64/ocaml/llvm/llvm_debuginfo.cmti
/usr/lib64/ocaml/llvm/llvm_debuginfo.cmx
/usr/lib64/ocaml/llvm/llvm_debuginfo.cmxa
/usr/lib64/ocaml/llvm/llvm_debuginfo.mli
/usr/lib64/ocaml/llvm/llvm_executionengine.a
/usr/lib64/ocaml/llvm/llvm_executionengine.cma
/usr/lib64/ocaml/llvm/llvm_executionengine.cmi
/usr/lib64/ocaml/llvm/llvm_executionengine.cmt
/usr/lib64/ocaml/llvm/llvm_executionengine.cmti
/usr/lib64/ocaml/llvm/llvm_executionengine.cmx
/usr/lib64/ocaml/llvm/llvm_executionengine.cmxa
/usr/lib64/ocaml/llvm/llvm_executionengine.mli
/usr/lib64/ocaml/llvm/llvm_irreader.a
/usr/lib64/ocaml/llvm/llvm_irreader.cma
/usr/lib64/ocaml/llvm/llvm_irreader.cmi
/usr/lib64/ocaml/llvm/llvm_irreader.cmt
/usr/lib64/ocaml/llvm/llvm_irreader.cmti
/usr/lib64/ocaml/llvm/llvm_irreader.cmx
/usr/lib64/ocaml/llvm/llvm_irreader.cmxa
/usr/lib64/ocaml/llvm/llvm_irreader.mli
/usr/lib64/ocaml/llvm/llvm_linker.a
/usr/lib64/ocaml/llvm/llvm_linker.cma
/usr/lib64/ocaml/llvm/llvm_linker.cmi
/usr/lib64/ocaml/llvm/llvm_linker.cmt
/usr/lib64/ocaml/llvm/llvm_linker.cmti
/usr/lib64/ocaml/llvm/llvm_linker.cmx
/usr/lib64/ocaml/llvm/llvm_linker.cmxa
/usr/lib64/ocaml/llvm/llvm_linker.mli
/usr/lib64/ocaml/llvm/llvm_passbuilder.a
/usr/lib64/ocaml/llvm/llvm_passbuilder.cma
/usr/lib64/ocaml/llvm/llvm_passbuilder.cmi
/usr/lib64/ocaml/llvm/llvm_passbuilder.cmt
/usr/lib64/ocaml/llvm/llvm_passbuilder.cmti
/usr/lib64/ocaml/llvm/llvm_passbuilder.cmx
/usr/lib64/ocaml/llvm/llvm_passbuilder.cmxa
/usr/lib64/ocaml/llvm/llvm_passbuilder.mli
/usr/lib64/ocaml/llvm/llvm_target.a
/usr/lib64/ocaml/llvm/llvm_target.cma
/usr/lib64/ocaml/llvm/llvm_target.cmi
/usr/lib64/ocaml/llvm/llvm_target.cmt
/usr/lib64/ocaml/llvm/llvm_target.cmti
/usr/lib64/ocaml/llvm/llvm_target.cmx
/usr/lib64/ocaml/llvm/llvm_target.cmxa
/usr/lib64/ocaml/llvm/llvm_target.mli
/usr/lib64/ocaml/llvm/llvm_transform_utils.a
/usr/lib64/ocaml/llvm/llvm_transform_utils.cma
/usr/lib64/ocaml/llvm/llvm_transform_utils.cmi
/usr/lib64/ocaml/llvm/llvm_transform_utils.cmt
/usr/lib64/ocaml/llvm/llvm_transform_utils.cmti
/usr/lib64/ocaml/llvm/llvm_transform_utils.cmx
/usr/lib64/ocaml/llvm/llvm_transform_utils.cmxa
/usr/lib64/ocaml/llvm/llvm_transform_utils.mli

